spring:
  datasource:
    url: jdbc:${DB_URL}
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true

app:
  version: 1.0.0
